// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: PowerPico

#ifndef UI_CHARTPAGE_H
#define UI_CHARTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ChartPage
extern void ui_ChartPage_screen_init(void);
extern void ui_ChartPage_screen_destroy(void);
extern lv_obj_t * ui_ChartPage;
void ui_chart_page_key_handler(void *key_event);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

