// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: PowerPico

#ifndef UI_SETPAGE_H
#define UI_SETPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetPage
extern void ui_SetPage_screen_init(void);
extern void ui_SetPage_screen_destroy(void);
extern lv_obj_t * ui_SetPage;
void ui_set_page_key_handler(void *key_event);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

