// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: PowerPico

#ifndef UI_PPSPAGE_H
#define UI_PPSPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PPSPage
void ui_PPSPage_screen_init(void);
void ui_PPSPage_screen_destroy(void);
extern lv_obj_t * ui_PPSPage;

void ui_pps_page_key_handler(void* key_event);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

