// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: PowerPico

#ifndef UI_STARTPAGE_H
#define UI_STARTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartPage
extern void ui_StartPage_screen_init(void);
extern void ui_StartPage_screen_destroy(void);
extern lv_obj_t * ui_StartPage;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

